/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/native";
import { Canvas, useLoader } from "@react-three/fiber";
import { TextureLoader } from "three/src/loaders/TextureLoader";

export default function BjakBagARModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/BjakBagAR.glb");

  const [colorMap, displacementMap, normalMap, roughnessMap, aoMap] = useLoader(
    TextureLoader,
    props.customColors.texture
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube001_RLExtr.geometry}
        material={materials["Material.004"]}
        position={[0, -0.2, 0.04]}
        rotation={[-0.05, 0, 0]}
        scale={[1, 1.46, 1]}
      />
      <mesh
        geometry={nodes.Cube001_RLExtr001.geometry}
        material={materials["Material.004"]}
        position={[0, -0.2, 0.04]}
        rotation={[-0.05, 0, 0]}
        scale={[1, 1.46, 1]}
      />
      <mesh
        geometry={nodes.Cube001_RLExtr002.geometry}
        material={materials["Material.002"]}
        position={[0, -0.2, 0.04]}
        rotation={[-0.05, 0, 0]}
        scale={[1, 1.46, 1]}
      />
      <mesh
        geometry={nodes.Plane001_RLExtr.geometry}
        material={materials["Material.004"]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Plane001_RLExtr001.geometry}
        material={materials["Material.004"]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Plane001_RLExtr002.geometry}
        material={materials["Material.004"]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Plane001_RLExtr003.geometry}
        material={materials["Material.004"]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Plane001_RLExtr004.geometry}
        material={materials["Material.004"]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Plane001_RLExtr005.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Cube003_RLExtr.geometry}
        material={materials["Material.002"]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Cube003_RLExtr001.geometry}
        material={materials["Material.004"]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Cube004_RLExtr.geometry}
        material={materials["Material.004"]}
        position={[0, 0, -0.63]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Cube004_RLExtr001.geometry}
        material={materials["Material.002"]}
        position={[0, 0, -0.63]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Cube006_RLExtr.geometry}
        material={materials["Material.004"]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.Cube006_RLExtr001.geometry}
        material={materials["Material.004"]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.Cube006_RLExtr002.geometry}
        material={materials["Material.004"]}
        scale={0.23}
      />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material}>
        <meshStandardMaterial
          displacementScale={0.001}
          map={colorMap}
          displacementMap={displacementMap}
          normalMap={normalMap}
          roughnessMap={roughnessMap}
          aoMap={aoMap}
        />
      </mesh>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 1.57, 0]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.001"]}
        position={[0, 0.12, -0.05]}
        rotation={[-Math.PI / 2, 1.57, 0]}
        scale={0.91}
      >
        <meshStandardMaterial
          displacementScale={0.001}
          map={colorMap}
          displacementMap={displacementMap}
          normalMap={normalMap}
          roughnessMap={roughnessMap}
          aoMap={aoMap}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[0, -0.2, 0.04]}
        rotation={[-0.05, 0, 0]}
        scale={[1, 1.46, 1]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.006"]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.004"]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.BezierCurve.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.004"]}
        position={[0, 0, -0.63]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.BezierCurve001.geometry}
        material={materials.Material}
        position={[0, 0, -0.61]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["Material.006"]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials["Material.004"]}
        scale={0.23}
      />
    </group>
  );
}

useGLTF.preload("/BjakBagAR.gltf");
