/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/native";
import { Canvas, useLoader } from "@react-three/fiber";
import { TextureLoader } from "three/src/loaders/TextureLoader";

export default function BjakHatARModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/BjakHatAR.glb");
  const { circularRingColor, fabricColor, primaryMetalColor, topPlateColor } =
    props.customColors;
  const [colorMap, displacementMap, normalMap, roughnessMap, aoMap] = useLoader(
    TextureLoader,
    props.customColors.texture
  );
  const isTextured = props.isTextured;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder005_RLExtr.geometry}
        material={materials.Metal}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.Cylinder005_RLExtr001.geometry}
        material={materials.Metal}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002_RLExtr.geometry}
        material={materials["Material.001"]}
      />
      {/* Circular Ring  */}
      <mesh
        geometry={nodes.Cylinder002_RLExtr001.geometry}
        material={materials.Metal}
        material-color={circularRingColor}
      />
      <mesh
        geometry={nodes.Cylinder008_RLExtr.geometry}
        material={materials.Metal}
      />
      <mesh
        geometry={nodes.Cylinder008_RLExtr001.geometry}
        material={materials.Metal}
      />
      <mesh
        geometry={nodes.Cylinder008_RLExtr002.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Cylinder005_RLExtr002.geometry}
        material={materials["Material.001"]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      {/* Fabric Color */}
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.Material}
        material-color={fabricColor}
      >
        {isTextured ? (
          <meshStandardMaterial
            displacementScale={0.001}
            map={colorMap}
            displacementMap={displacementMap}
            normalMap={normalMap}
            roughnessMap={roughnessMap}
            aoMap={aoMap}
          />
        ) : null}
      </mesh>
      {/* Primary Metal */}
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.002"]}
        material-color={primaryMetalColor}
      ></mesh>
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["Material.002"]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials["Material.003"]}
      />
      {/* Top Plate */}
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials["Material.003"]}
        material-color={topPlateColor}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/BjakHatAR.gltf");
