/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Canvas, useLoader } from "@react-three/fiber";
import { TextureLoader } from "three/src/loaders/TextureLoader";

export default function BjakBag({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/bjak_bag.glb");
  const [colorMap, displacementMap, normalMap, roughnessMap, aoMap] = useLoader(
    TextureLoader,
    props.customColors.texture
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.002"]}
        rotation={[-Math.PI / 2, 1.57, 0]}
        material-color={props.customColors.color1}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.001"]}
        position={[0, 0.13, -0.02]}
        rotation={[-Math.PI / 2, 1.57, 0]}
        scale={0.93}
        material-color={props.customColors.color2}
      />

      {/* Pocket */}
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.003"]}
        position={[0, -0.2, 0.04]}
        rotation={[-0.05, 0, 0]}
        scale={[1, 1.46, 1]}
        material-color={props.customColors.color3}
      >
        <meshStandardMaterial
          displacementScale={0.002}
          map={colorMap}
          displacementMap={displacementMap}
          normalMap={normalMap}
          roughnessMap={roughnessMap}
          aoMap={aoMap}
        />
      </mesh>

      {/* Buckle */}
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.004"]}
        scale={0.1}
        material-color={"green"}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.004"]}
        scale={0.3}
        material-color={"blue"}
      />

      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.004"]}
        position={[0, 0, -0.63]}
        scale={0.3}
        material-color={"pink"}
      />

      <mesh
        geometry={nodes.BezierCurve.geometry}
        material={materials["Material.002"]}
        material-color={"orange"}
      />
      <mesh
        geometry={nodes.BezierCurve001.geometry}
        material={materials["Material.002"]}
        position={[0, 0, -0.61]}
        material-color={"purple"}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["Material.004"]}
        material-color={"yellow"}
      />
    </group>
  );
}

useGLTF.preload("/bjak_bag.gltf");
